### ISSUE TITLE
Not available on pypi

### ISSUE THREAD

**Issue by siddhpant** [bryanforbes/discord-ext-typed-commands#10]
The package is not there on pypi, and consequently the `pip install` command mentioned in README fails.

**Comment by bryanforbes** [comment]
I haven't published this package quite yet. I'll probably wait until `discord.py` releases 1.5 in a few weeks. For now, you should be able to do the following:

```
pip install git+https://github.com/bryanforbes/discord-ext-typed-commands.git@master
```

I'll leave this open until I publish.

**Comment by siddhpant** [comment]
Alright, thanks!

**Comment by bryanforbes** [comment]
I went ahead and published this package on [pypi](https://pypi.org/project/discord-ext-typed-commands/) so installing via `pip install discord-ext-typed-commands` should work
